//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_21
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public string BuildingName { get; set; }
        public int RegionCode { get; set; }
        public int BranchCode { get; set; }
        public int OrganizationCode { get; set; }
        public int Funding1Quarter { get; set; }
        public int Funding2Quarter { get; set; }
        public int Funding3Quarter { get; set; }
        public int Funding4Quarter { get; set; }
        public System.DateTime ComissioningYear { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
